In [1]:
import pandas as pd
data = pd.read_csv("FTIR Tappert data for import.csv")
data

,Family,Species,Exudate type,Locality,650,652,654,656,658,660,...,Unnamed: 1748,Unnamed: 1749,Unnamed: 1750,Unnamed: 1751,Unnamed: 1752,Unnamed: 1753,Unnamed: 1754,Unnamed: 1755,Unnamed: 1756,Unnamed: 1757
0,Pinaceae,Abies balsamea,resin,"Edmonton, Alberta",0.147,0.151,0.153,0.153,0.153,0.152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Abies concolor,resin,"Seattle, WA",0.311,0.318,0.327,0.335,0.342,0.348,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Abies grandis,volatile-rich resin,"Falkland, British Columbia",0.706,0.706,0.702,0.696,0.690,0.686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Abies lasiocarpa,resin,"Fortress Mountain, Alberta",0.714,0.719,0.719,0.719,0.720,0.720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Abies lasiocarpa,volatile-rich resin,"Fortress Mountain, Alberta",0.953,0.954,0.952,0.949,0.942,0.936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Ginkgoaceae,Ginkgo biloba,gum,"Toronto, Ontario",0.610,0.610,0.620,0.620,0.620,0.630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Zamiaceae,Dioon purpusii,gum,"Edmonton, Alberta",1.397,1.406,1.399,1.397,1.400,1.398,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,Dioon spinulosum,gum,"Edmonton, Alberta",0.935,0.934,0.931,0.927,0.929,0.930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Cycadaceae,Cycas circinalis,gum,"Edmonton, Alberta",0.130,0.130,0.120,0.120,0.120,0.120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Welwitschiaceae,Welwitschia mirabilis,gum,"Arcata, CA",0.890,0.890,0.890,0.900,0.900,0.900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN